function run_probtrackx2(mask_file, output_dir, subject_dir, subject_reg_dir, log_file, target_file)
    system('module load fsl');
    % 检查是否提供了 target_file 参数
    if nargin < 6 || isempty(target_file)
        % 如果没有提供 target_file，构造不包含 --omatrix2 和 --target2 的命令
        cmd = sprintf('probtrackx2 -x %s --dir=%s -V 1 -l --modeuler --onewaycondition --omatrix1 --pd -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --xfm=%s --invxfm=%s --forcedir --opd -s %s -m %s > %s 2>&1', ...
            mask_file, ...
            output_dir, ...
            fullfile(subject_reg_dir, 'MNI_to_dti_FA_warp.nii.gz'), ...
            fullfile(subject_reg_dir, 'dti_FA_to_MNI_warp.nii.gz'), ...
            fullfile(subject_dir, 'merged'), ...
            fullfile(subject_dir, 'nodif_brain_mask'), ...
            log_file);
    else
        % 如果提供了 target_file，构造包含 --omatrix2 和 --target2 的命令
        cmd = sprintf('probtrackx2 -x %s --dir=%s -V 1 -l --modeuler --onewaycondition --omatrix1 --omatrix2 --target2=%s --pd -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --xfm=%s --invxfm=%s --forcedir --opd -s %s -m %s > %s 2>&1', ...
            mask_file, ...
            output_dir, ...
            target_file, ...
            fullfile(subject_reg_dir, 'MNI_to_dti_FA_warp.nii.gz'), ...
            fullfile(subject_reg_dir, 'dti_FA_to_MNI_warp.nii.gz'), ...
            fullfile(subject_dir, 'merged'), ...
            fullfile(subject_dir, 'nodif_brain_mask'), ...
            log_file);
    end

    % 执行命令
    [status, cmdout] = system(cmd);

    if status ~= 0
        error('Error executing command: %s\n%s', cmd, cmdout);
    else
        disp(['Command executed successfully: ', cmd]);
    end
end
